//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string TitlePay { get; set; }
        public string TransIDSystem { get; set; }
        public string CodeGenerator { get; set; }
        public string TransIDPay { get; set; }
        public string Amount { get; set; }
        public string ApiKey { get; set; }
        public Nullable<bool> ResultPay { get; set; }
        public string ResultCode { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    }
}
