//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetailSeo
    {
        public int OrderDetailSEOID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> RequestAmount { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> DeadLineDay { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
