//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetailAd
    {
        public int OrderDetailAdsID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Keyword { get; set; }
        public string Contents { get; set; }
        public string Description { get; set; }
        public string UrlSite { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblOrder tblOrder { get; set; }
    }
}
