//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblOrderDetailAds = new HashSet<tblOrderDetailAd>();
            this.tblOrderDetailSeos = new HashSet<tblOrderDetailSeo>();
            this.tblOrderDetailSocials = new HashSet<tblOrderDetailSocial>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<bool> IsPay { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual tblOrderType tblOrderType { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetailAd> tblOrderDetailAds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetailSeo> tblOrderDetailSeos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetailSocial> tblOrderDetailSocials { get; set; }
    }
}
