//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblOrderDetailAds = new HashSet<tblOrderDetailAd>();
            this.tblOrderDetailSocials = new HashSet<tblOrderDetailSocial>();
            this.tblOrderDetailSeos = new HashSet<tblOrderDetailSeo>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ProductDescription { get; set; }
        public string ProductDate { get; set; }
        public Nullable<bool> EnabledStatus { get; set; }
        public Nullable<byte> Discount { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UnitPriceFor { get; set; }
        public Nullable<int> MinLimit { get; set; }
        public Nullable<int> MaxLimit { get; set; }
        public string ServiceSocialID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<decimal> oneWord { get; set; }
        public Nullable<decimal> twoWord { get; set; }
        public Nullable<decimal> threeWord { get; set; }
        public Nullable<decimal> suppPerMonthOne { get; set; }
        public Nullable<decimal> suppPerMonthTwo { get; set; }
        public Nullable<decimal> suppPerMonthThree { get; set; }
        public Nullable<int> OneWordDay { get; set; }
        public Nullable<int> TwoWordDay { get; set; }
        public Nullable<int> ThreeWordDay { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetailAd> tblOrderDetailAds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetailSocial> tblOrderDetailSocials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetailSeo> tblOrderDetailSeos { get; set; }
    }
}
