//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> TransactionStatusID { get; set; }
        public string DateTime { get; set; }
        public Nullable<bool> IsSucsessfullPay { get; set; }
        public string TransNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CodeType { get; set; }
        public Nullable<int> OrderIdAddFound { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> PaymentID { get; set; }
    
        public virtual tblTransactionStatu tblTransactionStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblPayment tblPayment { get; set; }
    }
}
